export default [
  {
    "key": 0,
    "coffee": "Green Tea",
    "caffeineActual": 25,
    "caloriesActual": 0,
    "priceMGActual": 0.1,
    "category": "TEA",
    "calories": 0,
    "caffeine": 25,
    "price": 0.1,
    "silhouette": "tea"
  },
  {
    "key": 1,
    "coffee": "Espresso",
    "caffeineActual": 65,
    "caloriesActual": 5,
    "priceMGActual": 0.05,
    "category": "COFFEE",
    "calories": 5,
    "caffeine": 65,
    "price": 0.05,
    "silhouette": "espresso"
  },
  {
    "key": 2,
    "coffee": "Yerba Mate",
    "caffeineActual": 85,
    "caloriesActual": 5,
    "priceMGActual": 0.03,
    "category": "TEA",
    "calories": 5,
    "caffeine": 85,
    "price": 0.03,
    "silhouette": "tea"
  },
  {
    "key": 3,
    "coffee": "Double Espresso",
    "caffeineActual": 130,
    "caloriesActual": 6,
    "priceMGActual": 0.04,
    "category": "COFFEE",
    "calories": 6,
    "caffeine": 130,
    "price": 0.04,
    "silhouette": "espresso"
  },
  {
    "key": 4,
    "coffee": "Americano",
    "caffeineActual": 225,
    "caloriesActual": 15,
    "priceMGActual": 0.02,
    "category": "COFFEE",
    "calories": 15,
    "caffeine": 225,
    "price": 0.02,
    "silhouette": "large"
  },
  {
    "key": 5,
    "coffee": "Americano + milk",
    "caffeineActual": 225,
    "caloriesActual": 30,
    "priceMGActual": 0.02,
    "category": "COFFEE",
    "calories": 30,
    "caffeine": 225,
    "price": 0.02,
    "silhouette": "large"
  },
  {
    "key": 6,
    "coffee": "English Breakfast + 1 sugar",
    "caffeineActual": 56,
    "caloriesActual": 39,
    "priceMGActual": 0.13,
    "category": "TEA",
    "calories": 39,
    "caffeine": 26,
    "price": 0.13,
    "silhouette": "tea"
  },
  {
    "key": 7,
    "coffee": "Turkish Coffee",
    "caffeineActual": 25,
    "caloriesActual": 46,
    "priceMGActual": 0.12,
    "category": "COFFEE",
    "calories": 46,
    "caffeine": 25,
    "price": 0.12,
    "silhouette": "espresso"
  },
  {
    "key": 8,
    "coffee": "Red Bull",
    "caffeineActual": 77,
    "caloriesActual": 46,
    "priceMGActual": 0.03,
    "category": "SOFT DRINK",
    "calories": 46,
    "caffeine": 77,
    "price": 0.03,
    "silhouette": "redbull"
  },
  {
    "key": 9,
    "coffee": "Sugar-free Hot Chocolate",
    "caffeineActual": 5,
    "caloriesActual": 60,
    "priceMGActual": 1.26,
    "category": "CHOCOLATE",
    "calories": 60,
    "caffeine": 5,
    "price": 0.5,
    "silhouette": "large"
  },
  {
    "key": 10,
    "coffee": "Instant Coffee + 2 sugars",
    "caffeineActual": 47,
    "caloriesActual": 83,
    "priceMGActual": 0.01,
    "category": "COFFEE",
    "calories": 83,
    "caffeine": 47,
    "price": 0.01,
    "silhouette": "large"
  },
  {
    "key": 11,
    "coffee": "Café Crème",
    "caffeineActual": 225,
    "caloriesActual": 106,
    "priceMGActual": 0.02,
    "category": "COFFEE",
    "calories": 106,
    "caffeine": 225,
    "price": 0.02,
    "silhouette": "espresso"
  },
  {
    "key": 12,
    "coffee": "Cappuccino",
    "caffeineActual": 150,
    "caloriesActual": 120,
    "priceMGActual": 0.03,
    "category": "COFFEE",
    "calories": 120,
    "caffeine": 150,
    "price": 0.03,
    "silhouette": "tea"
  },
  {
    "key": 13,
    "coffee": "Pepsi",
    "caffeineActual": 38,
    "caloriesActual": 139,
    "priceMGActual": 0.03,
    "category": "SOFT DRINK",
    "calories": 138.6,
    "caffeine": 38,
    "price": 0.03,
    "silhouette": "can"
  },
  {
    "key": 14,
    "coffee": "Coke",
    "caffeineActual": 32,
    "caloriesActual": 150,
    "priceMGActual": 0.03,
    "category": "SOFT DRINK",
    "calories": 150,
    "caffeine": 32,
    "price": 0.03,
    "silhouette": "can"
  },
  {
    "key": 15,
    "coffee": "Latte",
    "caffeineActual": 150,
    "caloriesActual": 190,
    "priceMGActual": 0.03,
    "category": "COFFEE",
    "calories": 190,
    "caffeine": 150,
    "price": 0.03,
    "silhouette": "tea"
  },
  {
    "key": 16,
    "coffee": "Dark Chocolate Bar",
    "caffeineActual": 42,
    "caloriesActual": 205,
    "priceMGActual": 0.03,
    "category": "NON-DRINK",
    "calories": 205,
    "caffeine": 42,
    "price": 0.03,
    "silhouette": "chocolate"
  },
  {
    "key": 17,
    "coffee": "Mocha (small)",
    "caffeineActual": 195,
    "caloriesActual": 220,
    "priceMGActual": 0.02,
    "category": "COFFEE",
    "calories": 220,
    "caffeine": 195,
    "price": 0.02,
    "silhouette": "espresso"
  },
  {
    "key": 18,
    "coffee": "Chai Latte",
    "caffeineActual": 95,
    "caloriesActual": 240,
    "priceMGActual": 0.05,
    "category": "TEA",
    "calories": 240,
    "caffeine": 95,
    "price": 0.05,
    "silhouette": "tea"
  },
  {
    "key": 19,
    "coffee": "Lucozade",
    "caffeineActual": 46,
    "caloriesActual": 266,
    "priceMGActual": 0.02,
    "category": "SOFT DRINK",
    "calories": 266,
    "caffeine": 46,
    "price": 0.02,
    "silhouette": "lucozade"
  },
  {
    "key": 20,
    "coffee": "Mountain Dew",
    "caffeineActual": 91,
    "caloriesActual": 290,
    "priceMGActual": 0.01,
    "category": "SOFT DRINK",
    "calories": 290,
    "caffeine": 91,
    "price": 0.01,
    "silhouette": "mtn-dew"
  },
  {
    "key": 21,
    "coffee": "Spiced Hot Chocolate",
    "caffeineActual": 25,
    "caloriesActual": 320,
    "priceMGActual": 0.24,
    "category": "CHOCOLATE",
    "calories": 320,
    "caffeine": 25,
    "price": 0.24,
    "silhouette": "large"
  },
  {
    "key": 22,
    "coffee": "Ghana-Java Hot Chocolate",
    "caffeineActual": 25,
    "caloriesActual": 380,
    "priceMGActual": 0.24,
    "category": "CHOCOLATE",
    "calories": 380,
    "caffeine": 25,
    "price": 0.24,
    "silhouette": "large"
  },
  {
    "key": 23,
    "coffee": "Vanilla Cream Frappuccino",
    "caffeineActual": 65,
    "caloriesActual": 400,
    "priceMGActual": 0.1,
    "category": "COFFEE",
    "calories": 400,
    "caffeine": 65,
    "price": 0.1,
    "silhouette": "iced"
  },
  {
    "key": 24,
    "coffee": "Frappuccino",
    "caffeineActual": 110,
    "caloriesActual": 410,
    "priceMGActual": 0.06,
    "category": "COFFEE",
    "calories": 410,
    "caffeine": 110,
    "price": 0.06,
    "silhouette": "iced"
  },
  {
    "key": 25,
    "coffee": "Caramel Sticky Mocha",
    "caffeineActual": 110,
    "caloriesActual": 420,
    "priceMGActual": 0.05,
    "category": "COFFEE",
    "calories": 420,
    "caffeine": 110,
    "price": 0.05,
    "silhouette": "espresso"
  },
  {
    "key": 26,
    "coffee": "Mocha (big)",
    "caffeineActual": 150,
    "caloriesActual": 430,
    "priceMGActual": 0.04,
    "category": "COFFEE",
    "calories": 430,
    "caffeine": 150,
    "price": 0.04,
    "silhouette": "espresso"
  },
  {
    "key": 27,
    "coffee": "Hot choc + marshmallows",
    "caffeineActual": 25,
    "caloriesActual": 480,
    "priceMGActual": 0.23,
    "category": "CHOCOLATE",
    "calories": 480,
    "caffeine": 25,
    "price": 0.23,
    "silhouette": "espresso"
  },
  {
    "key": 28,
    "coffee": "Coffee Ice Cream",
    "caffeineActual": 48,
    "caloriesActual": 540,
    "priceMGActual": 0.06,
    "category": "NON-DRINK",
    "calories": 500,
    "caffeine": 48,
    "price": 0.06,
    "silhouette": "coffee-ice-cream"
  }
]
